# Generated by Django 3.0 on 2020-08-07 23:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_empleado_habilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='hoja_vidal',
            field=ckeditor.fields.RichTextField(default='vacio'),
            preserve_default=False,
        ),
    ]
